#pragma once

// place overrides here
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#undef  TAPPING_TERM
#define TAPPING_TERM 175

#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 2
//#undef STM32_ONBOARD_EEPROM_SIZE
//#define STM32_ONBOARD_EEPROM_SIZE 4096
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
