#pragma once

// place overrides here
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#undef  TAPPING_TERM
#define TAPPING_TERM 175

#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 2

#define VIAL_UNLOCK_COMBO_ROWS { 0, 6 }
#define VIAL_UNLOCK_COMBO_COLS { 2, 6 }
#define VIAL_KEYBOARD_UID {0xCC, 0xAA, 0xB0, 0x6F, 0x9B, 0x80, 0xF3, 0xF5}

#define DYNAMIC_KEYMAP_LAYER_COUNT 8
